version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gastuandat_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          memory: 800M
          cpus: '0.6'
    networks:
      - gastuandat-network

  frontend:
    build:
      context: ../kiotviet-dashboard
      dockerfile: Dockerfile
    container_name: gastuandat_frontend
    ports:
      - "3000:3000"
    env_file:
      - ../kiotviet-dashboard/.env
    restart: always
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '0.4'
    networks:
      - gastuandat-network

networks:
  gastuandat-network:
    driver: bridge
