spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: GasTuanDat
  datasource:
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update   # dev dùng
    show-sql: true
server:
  port: 8080
  servlet:
    context-path: /api/v1
jwt:
  signerKey: ${APP_SECRET}
  expiration: 3600
  refreshExpiration: 604800